services:
    nginx:
        build: ./requirements/nginx
        ports: 
            - "443:443"
        expose:
            - "9000"
        env_file:
            - .env
        volumes:
            - wp-file:/var/www/html
            - adminer-file:/var/www/html/adminer
        networks:
            - Inception
        depends_on:
            - wordpress

    mariadb:
        build: ./requirements/mariadb
        expose:
            - "3306"
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - Inception
        init: true

    wordpress:
        build: ./requirements/wordpress
        expose:
            - "9000"
            - "3306"
            - "6379"
        networks:
            - Inception
        env_file:
            - .env
        volumes:
            - wp-file:/var/www/html
        depends_on:
            - mariadb
            - redis

    redis:
        build: ./requirements/bonus/redis
        expose:
            - "6379"
        networks:
            - Inception
        env_file:
            - .env

    ftp:
        build: ./requirements/bonus/ftp
        ports:
            - "21:21"
            - "20:20"
            - "40000-40025:40000-40025"
            # explicit ssl
			# not needed, since our 21 port is already implicit ssl
			# - "990:990"
            # ssh connection
			# we deal with this later
            # - "22:22"
        volumes:
            - wp-file:/ftp
        env_file:
            - .env
        # ftp seg-faults for nooo fucking reason
        restart: on-failure

    adminer:
        build: ./requirements/bonus/adminer
        expose:
            - "8000"
        networks:
            - Inception
        env_file:
            - .env
        volumes:
            - adminer-file:/var/www/html/adminer	

    gitea:
        build: ./requirements/bonus/gitea 
        ports:
            - "80:80"
        env_file:
            - .env
        networks:
            - Inception

    # git:
    #    build: ./requirements/bonus/git
    #    ports:
    #        - "4242:22" # open ssh port in another port since well, i kinda need ssh :P
    #    volumes:
    #        - git-data:/home/git/
    #    env_file:
    #        - .env

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            device: /home/cshi-xia/data/db
            o: bind

    wp-file:
        driver: local
        driver_opts:
            type: none
            device: /home/cshi-xia/data/wp

            o: bind

    adminer-file:
        driver: local
        driver_opts:
            type: none
            device: /home/cshi-xia/data/admin
            o: bind

    git-data:
        driver: local
        driver_opts:
            type: none
            device: /home/cshi-xia/data/git
            o: bind

networks:
    Inception:
