services:
  nginx:
    build: ./requirements/nginx
    ports: 
      - "443:443"
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp-file:/var/www/html
    networks:
      - Inception
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb    
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - Inception
    init: true

  wordpress:
    build: ./requirements/wordpress
    expose:
      - "9000"
      - "3306"
      - "6379"
    networks:
      - Inception
    env_file:
      - .env
    volumes:
      - wp-file:/var/www/html
    depends_on:
      - mariadb
      - redis

  redis:
    build: ./requirements/bonus/redis
    expose:
      - "6379"
    networks:
      - Inception
    env_file:
      - .env

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/cshi-xia/data/db
      o: bind

  wp-file:
    driver: local
    driver_opts:
      type: none
      device: /home/cshi-xia/data/wp
      o: bind

networks:
  Inception:
