services:
  nginx:
    build: ./requirements/nginx
    ports: 
      - "443:443"
    expose:
      - "9000:9000"
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb    
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db-data:
